Mvc-no-autenticacion/Models/ErrorViewModel.cs
using System;

namespace Mvc_no_autenticacion.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc-no-autenticacion/Models/Libro.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mvc_no_autenticacion.Models
{
    public class Libro
    {
       [Key]
       public int Id { get; set; }

       [Required(ErrorMessage = "El título es obligatorio")]
       [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y máximo {1} caracteres", MinimumLength = 3)]
       [Display(Name = "Título")]
       public string Titulo { get; set; }

       [Required(ErrorMessage = "El Descripción es obligatoria")]
       [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y máximo {1} caracteres", MinimumLength = 3)]
       [Display(Name = "Descripción")]
       public string Descripcion { get; set; }

       [Required(ErrorMessage = "La fecha es obligatoria")]
       [DataType(DataType.Date)]
       [Display(Name = "Fecha de Lanzamiento")]
       public DateTime FechaLanzamiento { get; set; }

       [Required(ErrorMessage = "El autor es obligatorio")]
       public string Autor { get; set; }

       [Required(ErrorMessage = "El precio es obligatorio")]
       public int Precio { get; set; }

    }
}

Mvc-no-autenticacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mvc_no_autenticacion.Models;

namespace Mvc_no_autenticacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc-no-autenticacion/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mvc_no_autenticacion.DataToDb;
using Mvc_no_autenticacion.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mvc_no_autenticacion.Controllers
{
    public class LibrosController : Controller
    {
        private readonly AplicationDbContext _context;

        public LibrosController(AplicationDbContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            IEnumerable<Libro> listLibros = _context.Libro;
            return View(listLibros);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Libro.Add(libro);
                _context.SaveChanges();
                TempData["mensaje"] = "El Libro se creo correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();

            }

            var libro = _context.Libro.Find(id);

            if(libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Libro.Update(libro);
                _context.SaveChanges();
                TempData["mensaje"] = "El Libro se actualizo correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();

            }

            var libro = _context.Libro.Find(id);

            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteLibro(int? id)
        {
            var libro = _context.Libro.Find(id);
            if (libro == null)
            {
                return NotFound();
            }

                _context.Libro.Remove(libro);
                _context.SaveChanges();
                TempData["mensaje"] = "El Libro se elimino correctamente";
                return RedirectToAction("Index");
            
        }
    }
}

Mvc-no-autenticacion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc-no-autenticacion/Views/Libros/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Mvc_no_autenticacion.Models.Libro

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear un Libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit"  value="Crear Libro" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts{
@{ <partial name="_ValidationScriptsPartial"/>}
}

Mvc-no-autenticacion/Views/Libros/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Mvc_no_autenticacion.Models.Libro

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar un Libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteLibro">
                <input type="hidden" asp-for="Id"/>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" disabled/>
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" disabled/>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" disabled/>
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" disabled/>
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" disabled/>
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit"  value="Eliminar Libro" class="btn btn-danger" />
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts{
@{ <partial name="_ValidationScriptsPartial"/>}
}

Mvc-no-autenticacion/Views/Libros/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Mvc_no_autenticacion.Models.Libro

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar un Libro</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">
                <input type="hidden" asp-for="Id"/>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaLanzamiento" class="control-label"></label>
                    <input asp-for="FechaLanzamiento" class="form-control" />
                    <span asp-validation-for="FechaLanzamiento" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit"  value="Editar Libro" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts{
@{ <partial name="_ValidationScriptsPartial"/>}
}

Mvc-no-autenticacion/Views/Libros/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Mvc_no_autenticacion.Models.Libro>
<h1>Bienvenido Alex</h1>

<div class="container">
    @if (TempData["mensaje"] != null)
        {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" date-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        }
    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de Libros</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Libros">Ageregar</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(m => m.Id)
                            </td>
                            <td>
                                @Html.DisplayNameFor(m => m.Titulo)
                            </td>
                            <td>
                                @Html.DisplayNameFor(m => m.Descripcion)
                            </td>
                            <td>
                                @Html.DisplayNameFor(m => m.FechaLanzamiento)
                            </td>
                            <td>
                                @Html.DisplayNameFor(m => m.Autor)
                            </td>
                            <td>
                                @Html.DisplayNameFor(m => m.Precio)
                            </td>
                            <td>
                                Acciones
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.Titulo
                                </td>
                                <td>
                                    @item.Descripcion
                                </td>
                                <td>
                                    @item.FechaLanzamiento
                                </td>
                                <td>
                                    @item.Autor
                                </td>
                                <td>
                                    @item.Precio
                                </td>
                                <td>
                                    <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                                    <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No Existen Registros</p>
            }
    </div>
</div>

Mvc-no-autenticacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc_no_autenticacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc_no_autenticacion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Mvc_no_autenticacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>